Fix build error due to missing includes
fatal error: fastrtps/participant/Participant.h: No such file or directory
fatal error: fastrtps/TopicDataType.h: No such file or directory

The build fails due to incorrect include directory. "fastrtps/include" is
already part of FastRTPS_INCLUDE_DIR, no need to append.